webempresarial/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.BlogListView.as_view(), name="blog"),
    path("<int:pk>/", views.BlogDetailView.as_view(), name="detail_blog"),
    path("create/", views.BlogCreateView.as_view(), name="create_blog"),
    path("update/<int:pk>/", views.BlogUpdateView.as_view(), name="update_blog"),
    path("delete/<int:pk>/", views.BlogDeleteView.as_view(), name="delete_blog"),
    ### CATEGORÍAS
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path("categories/create/", views.CategoryCreateView.as_view(), name="create_category"),
    path("categories/update/<int:pk>/", views.CategoryUpdateView.as_view(), name="update_category"),
    path("categories/delete/<int:pk>/", views.CategoryDeleteView.as_view(), name="delete_category"),
]

webempresarial/contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.ContactTemplateView.as_view(), name="contact"),
    path("update/<int:pk>/", views.ContactUpdateView.as_view(), name="update_contact"),
]

webempresarial/webempresarial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from registration import urls
from core import urls
from sample import urls
from social import urls
from about import urls
from services import urls
from store import urls
from contact import urls
from blog import urls

urlpatterns = [
    # URLS DJANGO
    path('admin/', admin.site.urls),
    path("accounts/", include("registration.urls")),
    # CORE - WEBEMPRESARIAL
    path("", include("core.urls")),
    # SAMPLE - WEBEMPRESARIAL
    path("sample/", include("sample.urls")),
    # SOCIAL - WEBEMPRESARIAL
    path("social/", include("social.urls")),
    # ABOUT - WEBEMPRESARIAL
    path("about/", include("about.urls")),
    # SERVICES - WEBEMPRESARIAL
    path("services/", include("services.urls")),
    # STORE - WEBEMPRESARIAL
    path("store/", include("store.urls")),
    # CONTACT - WEBEMPRESARIAL
    path("contact/", include("contact.urls")),
    # BLOG - WEBEMPRESARIAL
    path("blog/", include("blog.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webempresarial/contact/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class Contact(models.Model):
    title = models.CharField(max_length=100, verbose_name="Título")
    email = models.EmailField(max_length=100, verbose_name="Email")
    phone_number = PhoneNumberField(verbose_name="Número de teléfono")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Última actualización")

    class Meta:
        verbose_name = "Contacto"
        verbose_name_plural = "Contactos"
    
    def __str__(self):
        return self.title

webempresarial/contact/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django import forms
from .models import Contact

# Método de seguridad - Solo usuarios administradores
class StaffIsRequiredMixin(object):
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StaffIsRequiredMixin, self).dispatch(request, *args, **kwargs)

# Create your views here.
class ContactTemplateView(TemplateView):
    template_name = "contact/contact.html"

@method_decorator(staff_member_required, name="dispatch")
class ContactUpdateView(UpdateView):
    model = Contact
    template_name = "forms/form_update.html"
    fields = ["title", "email", "phone_number"]
    success_url = reverse_lazy("contact")

    def get_form(self, form_class = None): 
        form = super(ContactUpdateView, self).get_form()
        form.fields["title"].widget = forms.TextInput(attrs={"class": "form-control mb-2", 'placeholder':"Título"})
        form.fields["email"].widget = forms.TextInput(attrs={"class": "form-control mb-2", 'placeholder':"Email"})
        form.fields["phone_number"].widget = forms.TextInput(attrs={"class": "form-control mb-2", 'placeholder':"Número de teléfono"})
        return form

webempresarial/contact/templates/contact/contact.html
{% extends "core/base.html" %} 
{% block content %}
{% load static %}
<section class="page-section about-heading">
  {% load contact_extra %}
  {% get_contact_list as contact_list %}
  {% for contact in contact_list %}
  <div class="container">
    <img
      class="img-fluid rounded about-heading-img mb-3 mb-lg-0"
      src="{% static 'core/img/contact.jpg' %}" 
      alt=""
    />
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Envíanos tus dudas</span>
              <span class="section-heading-lower">{{contact.title}}</span>
            </h2>

            <!-- Formulario de contacto -->
            <form>
              <div class="form-group">
                <label class="h2">Datos:</label>
                <div class="input-group">
                </div>
              </div>
              <div class="form-group">
                <label class="h3">{{contact.email}}</label>
                <div class="input-group">
                </div>
              </div>
              <div class="form-group">
                <label class="h4">{{contact.phone_number}}</label>
                <div class="input-group">
                </div>
              </div>
              {% if request.user.is_staff %}
              <div class="intro-button mx-auto mt-5">
                <a class="btn btn-primary btn-block" href="{% url 'update_contact' contact.id %}">Editar</a>
              </div>
        {% endif %}
            </form>
            <!-- Fin formulario de contacto -->
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</section>
{% endblock content %}